### PR TITLE
Completed Pair programming Exercise with Berkay Akbas for Decoding Morse Code

### PR DESCRIPTION
**Pull request by AsimKhan2019**
Complete the exercise and practiced it in the IRB Ubuntu Terminal environment. 

Created 3 methods 

get_singleLetter
get_theword
get_finalMessage

Passed in global variables to access string data across all the methods and functions. Used do loop to process through letters and words to make a complete word and then a final complete message. 

Created a morse dictionary to hold all the morse code with their respective single character values.

### CODE REVIEW

**Review by DammyShittu — COMMENTED** [review]
Hi @AsimKhan2019 @Berkay-akbas,

While you made a great effort in this project, I cannot proceed to review your code.

## Invalid Code Review Request

### You have not set up linters

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by AsimKhan2019** [comment]
@DammyShittu I am so sorry for the mistake I will add the files to the repository.

**Review by tufoinnkuo10 — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi @AsimKhan2019 

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- No linter errors

<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by AsimKhan2019** [comment]
@tufoinnkuo10 Thank you for the approval

**Comment by AsimKhan2019** [comment]
@tufoinnkuo10 Thank you for the approval

**Pull request merged**
